port: 3000
name: app

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password

host: 0.0.0.0
port_reuse: true
process_count: 1
database_url: postgres://postgres:password@db:5432/app_development
auto_reload: true
