port: 3000
name: app

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
    
host: 0.0.0.0
port_reuse: false
process_count: 1
database_url: postgres://postgres:password@localhost:5432/app_test
auto_reload: false
